### ISSUE TITLE
Organize package.json with child nodes

### ISSUE THREAD

**Issue by edreamleo** [boltex/leojs#10]
See PR #23 for the ekr-scripts2 branch.

package.json contains a lot of data. Make the JSON as Leonine as possible by adding separate nodes for various entries.

- [x] Write: script: split contributes/command section of package.json.
- [x] Write: script: split the "contributes/menus" section of package.json.
- [x] Write: Script: split the "contributes/keybindings" section of package.json.
- [x] Move the generated nodes to be children of `@clean package.json`.

After running these scripts, it will be easy to alphabetize nodes and organize them with organizer nodes.

**Comment by boltex** [comment]
Some information about the package.json file:

package.json, although not containing any code, is still a major cornerstone of the extension for the GUI side of things. 

It defines available commands, and their visibility/availability (in the command palette or actual placement and shown/hidden conditions) of any icons, along with the available keybindings for most of them.

Most importantly, commands in package.json are defined differently for being invoked with focus at either the outline pane, or the body pane, as it is the most (maybe only) reliable way to distinguish exact focus placement as a command is invoked. The "_fo" suffix is used in the case of commands detected as being invoked with focus in the outline pane, "fo" meaning "From Outline".

Note: Leo's keybindings have no interest to be detected while focus is on any other of vscode's gui controls, except in some rare occasions.

**Comment by edreamleo** [comment]
@boltex Thanks for your comment. Without your comment, I would not have noticed the suffix, and would have had no idea that focus mediates the data.

**Comment by boltex** [comment]
oops I didnt notice this from my filters in vscode, and did it on another branch!

**Comment by boltex** [comment]
Those sections have been split since Dec 2020, (Nice scripts by the way, thanks to @edreamleo !) 

I just seem to have forgotten to close this issue.
