### ISSUE TITLE
Forcefully show Log-Pane only at the very first startup & on version updates.

### ISSUE THREAD

**Issue by edreamleo** [boltex/leojs#124]
Regardless of vs-code's `debug.internalConsoleOptions` setting, LeoJS shows the Console on startup.

This is a minor irritation, but I would like to see it fixed.

**Update**:

As a workaround, I added a shortcut (`Alt-Ctrl-Y`) for "View: Previous Panel". This allows me to open the Leo Log with:

`Ctrl-Shift-Y` (`Toggle Debug Console`) followed by `Alt-Shift-Y`.

**Comment by boltex** [comment]
@edreamleo Thanks for this report.

I know Leojs (and leointeg) try to show their log pane when starting up. Is that what you are referring to?  (perhaps I should reconsider that behavior given there are now many ways to execute the 'show Log Pane' command)

...or is it the specific 'Console' as shown in this screenshot? : https://code.visualstudio.com/docs/editor/debugging

...or the generic 'Output pane' region as a whole, shown here labeled as 'D' in this screenshot? : 
 https://code.visualstudio.com/docs/getstarted/userinterface 

Note: In windows you can easily 'Drag' a rectangle on screen to capture a screenshot with the Shift+Windows Key+S in case you want to capture a region of your screen and paste it directly in this thread.

**Comment by edreamleo** [comment]
@boltex 

Doh.  I see that "generic" output region shows the Leo log, so there is good reason for LeoJS's existing behavior.

To answer your question: I was referring to the generic 'Output pane' region as a whole, that is, the region that `Shift-Control-Y` affects. On startup, that region shows Leo's log. The first Shift-Control-Y changes the focus to the (empty) 'Debug Console'. The second Shift-Control-Y closes the entire region.

**Summary**

Imo, this is a minor issue. It can easily wait until LeoJS 1.0.1 :-)

If possible, I would prefer hiding the entire region on startup. A `toggle-leo-log` command could show/hide the generic 'Output pane' region, showing Leo's log when making the region visible.

**Comment by edreamleo** [comment]
@boltex Alternatively, perhaps the Leo console could be moved to left-hand area, the area that contains 'Outline', 'Timeline', etc.

Again, this can wait until well after LeoJS 1.0.

**Comment by boltex** [comment]
@edreamleo Having the leo log pane on the left instead of below as an output pane is a great idea! 
I'll make it switchable with an options setting. (i changed the title of this issue to match this idea)

**Comment by boltex** [comment]
@edreamleo I forgot to mention the often used and well-known CTRL+J shortcut by VSCode users that toggles (open/close) the whole bottom panel itself.

**Comment by boltex** [comment]
@edreamleo You're right that it's annoying to have the log pane **forcefully** open the bottom output pane to show itself at startup. 

 I'll make the log pane be forcefully shown **only at the very first startup** when LeoJS is first installed, or, when a new version update of LeoJS just got downloaded & started.

**Comment by edreamleo** [comment]
@boltex Thanks for this change.

**Comment by boltex** [comment]
@edreamleo I've decided to revisit the issue of the log pane visibility in LeoJS after our discussion in which running a script did not forcefully show the log pane when `g.es` was invoked in the script. I think this is one of the rare occasions which it should be 'shown'. 

So I'll check the `g.app.inScript` flag in `g.es`:  If its true, (in the middle of running a script invoked by the users's `CTRL+B` or an `@button` click) then I'll make sure the log pane is shown when this g.es call tries to output to it. 

Leo itself also makes the log pane visible when a script is run with an 'g.es' in it. 😄

**Comment by edreamleo** [comment]
@boltex Thanks for your comments.
