### ISSUE TITLE
Highlight the demo videos in the readme

### ISSUE THREAD

**Issue by edreamleo** [boltex/leojs#125]
Félix, you've done a great job with the demos. Make sure people will find them!

I suggest creating a separate major section, say `Demo videos` just before or after the `Features` section.

**Comment by boltex** [comment]
@edreamleo 

Thanks Edward!! 

On that same note: Although I did mention the repository showcasing 'Leo scripts for various use-cases' at https://github.com/boltex/scripting-samples-leojs , I think I forgot to mention in the forums and in the documentation that I made a repository for a sample 'extension plugin' for LeoJS --> https://github.com/boltex/extension-sample-leojs

I think this may interest @tbpassin 😄

**Comment by tbpassin** [comment]
Yes, it will.
