### ISSUE TITLE
Saving a .leo does not write to Leo's log

### ISSUE THREAD

**Issue by edreamleo** [boltex/leojs#126]
Control-S *usually* writes a "saved" message to Leo's log. However, if the desktop version of Leo is open, LeoJS opens a faux "dialog" (at the top of the vs-code window) asking whether to overwrite the file.

I answered yes. Forever after nothing more appeared in the Leo log.

This issue seems unrelated to #124.

**Comment by boltex** [comment]
@edreamleo 

Thanks for filing this issue. But I'm not sure I understand the scenario you've described. 

When you say: With both opened at the same time, I guess you had the same Leo file opened in both? Did you save with CTRL+S in leojs or in Leo? Did the other program not show a dialog saying "The leo file has changed outside of Leo, Reload?" or something similar to that upon saving in the other one? (as it should)

... and indeed, hitting 'YES' would only reload the file and its external files without writing 'saved leo file' messages in the log pane.

In any case, could you reproduce the issue if you can? and most importantly: grab a screenshot of the dialog? (or the whole desktop so I can see what the situation is more clearly) 

Many Thanks!

**Comment by edreamleo** [comment]
@boltex Scenario (I'm not sure it will duplicate the issue).  I'm making notes as I go.

- Open desktop Leo containing leoPy.leo.
- Open LeoJS with `code .` from the same directory.
- Change some body text using LeoJS.
- Save (Ctrl-S) in LeoJS.
- The following dialog appears in desktop Leo.

![image](https://github.com/boltex/leojs/assets/592928/000fb6f6-407d-4751-a038-dc01488b7fef)

- Choose Yes.  The body text has changed in desktop Leo.

Change the text again in LeoJS and again Save (Ctrl-S) in LeoJS. Now *two* dialogs appear. The first in Leo (as before) and another in LeoJS:

![image](https://github.com/boltex/leojs/assets/592928/dd70407e-bc01-40ea-8a08-d4433fa5c9e5)

Choose "Yes" in both dialogs.

- Open the Console area in LeoJS with Shift-Control-Y:

![image](https://github.com/boltex/leojs/assets/592928/f431a094-dbbc-4de0-af44-267dd6abf177)

Notice that there is no saved message in Leo's Log (in vs-code).  But perhaps this is OK because of the reverted and reloaded message.

- Save again in vs-code.  Yes, there is a save message.

**Summary**

I do not see any strange behavior. I'll close this issue and reopen only if I can replicate.

**Comment by edreamleo** [comment]
Closing this issue because I can't replicate any concerning behavior.
