### ISSUE TITLE
LeoJS - Document Section - "Show Log Pane" Control Does Not Appear To Do Anything.

### ISSUE THREAD

**Issue by tbpassin** [boltex/leojs#131]
This leaves me wondering what the control is expected to do.  All I see is that the icon for it gets removed.  Nothing happens to the actual log output.

```
LeoJS 0.2.13, master branch, build e696124
2024-04-28 22:42:42 -0400
Node.js v18.18.2, VSCode version 1.88.1
Windows 10 Home x64 (build 10.0.19045)
```

**Comment by boltex** [comment]
@tbpassin  Hmm, not sure I understand what you are describing... 

This is meant to make the log pane appear in case it was hidden or closed. (just like 'show body' or 'show outline' )

Icons for commands can appear at multiple places in the interface. **Please take a screenshot** of the area where you see that 'Show Log Pane' command icon.  

(On windows, drag a rectangle on screen and paste it here when replying with this shortcut: `Shift + Windows-Key + S` )

I tried using it myself, Here is the bottom of my vscode window while my mouse is hovering the 'Show Log Pane' icon (the output panels/terminal panels are closed, only the body pane is on the right)
![image](https://github.com/boltex/leojs/assets/847716/9ca7b33d-174d-4b4b-8ae2-39b92e32963a)

After pressing it, the log pane appears! 😄 
![image](https://github.com/boltex/leojs/assets/847716/7b4e6970-bf5d-4207-902d-3ed3e21f3c3a)

Anyways, I hope this example can help you give more details (and screenshots! hehe!) to clarify what was the experience you had with the 'Show Log Pane' command and/or icon.

Thanks again for your dedicated persistence in learning and trying out vscode and leojs!!

**Comment by tbpassin** [comment]
Now I see.  I thought it was a toggle.  After I manually closed that output pane by clicking its "X" box, the "Show Log Pane" control did open it again.

I had expected it would hide or close the output pane if I clicked it when the pane was visible, and it didn't do anything.
