### ISSUE TITLE
Implement leoMarkup.py to support @adoc, @pandoc and @sphinx nodes and related commands.

### ISSUE THREAD

**Issue by boltex** [boltex/leojs#157]
Similar to the issue 80 https://github.com/boltex/leojs/issues/80 

Implement leoMarkup.py to support @adoc, @pandoc and @sphinx nodes and related commands.

**Comment by boltex** [comment]
**This is now done in the devel branch**. It's still untested. (Please test if you can and report any issues!)

**Comment by ranvik14** [comment]
> **This is now done in the devel branch**. It's still untested. (Please test if you can and report any issues!)

@boltex : I'll start testing the @sphinx implementation early next week.

**Comment by boltex** [comment]
@ranvik I've fixed it and will release it in 1.0.2. If there are problems or bugs remaining I will fix them in 1.0.3 😄
