### ISSUE TITLE
github discussions

### ISSUE THREAD

**Issue by kghenderson** [boltex/leojs#41]
Hi Felix, perhaps it might be possible to open the discussions and perhaps wiki sections here on github.
I'd like to contribute some comments here, i.e. some possible advantages of this platform (leojs), and try to draw some attention this project :-D

**Comment by boltex** [comment]
@kghenderson  Will do!

**Comment by boltex** [comment]
Should be enabled now : https://github.com/boltex/leojs/discussions/45 

Thanks again for this suggestion!
