### ISSUE TITLE
The name of the body tab should be f"LeoJS: {c.p.h}"

### ISSUE THREAD

**Issue by edreamleo** [boltex/leojs#67]
The present name is "LEOJS: BODY".

At minimum, it should be "LeoJS: Body". There is no need for all caps.

A static name is fine during startup.

After startup, I recommend the following:

- The name of the tab should be `LeoJS: ` followed by `c.p.h`.
- It's fine not to update the tab's name while rapidly changing `c.p`.
  In other words, it may be best to update the tab's name at idle time.

**Comment by boltex** [comment]
Good idea!

I only have access to parts of the uri to display, as interpolated strings (shown here: https://code.visualstudio.com/api/references/contribution-points#contributes.resourceLabelFormatters ) 

So I've made it "LeoJS: Body" for now in #68

**Comment by edreamleo** [comment]
On Wed, Dec 13, 2023 at 11:13 PM Felix ***@***.***> wrote:

> Good idea!
>
> I only have access to parts of the uri to display, as interpolated strings
> (shown here:
> https://code.visualstudio.com/api/references/contribution-points#contributes.resourceLabelFormatters
> )
>
> So I've made it "LeoJS: Body" for now in #68
> <https://github.com/boltex/leojs/pull/68>
>
Alright. Until we resolve #61 <https://github.com/boltex/leojs/issues/61>
perhaps you could output c.p.h when LeoJS changes nodes.

Edward

**Comment by edreamleo** [comment]
@boltex Oops: I meant to say, "output c.p.h *to the console*".
