### ISSUE TITLE
Where Is The Nav Pane?

### ISSUE THREAD

**Issue by tbpassin** [boltex/leojs#85]
I thought I remembered that leoInteg had a working Nav tab, but I can't find it in leoJS.  I use the Nav tab for almost all my searches, so this is important to me.
```
LeoJS 0.2.5, master branch, build 2f8dca6
2023-12-16 23:36:29 -0500
Node.js v18.15.0, VSCode version 1.85.0
Windows 10 Home x64 (build 10.0.19045)
      home: C:\Users\tom
leo-editor: C:\Users\tom\.vscode\extensions\boltex.leojs-0.2.5
```

**Comment by boltex** [comment]
@tbpassin The nav pane controls are right there at the top of the find pane 😄  You can even use it to search for 'tag' ! 

_(Thanks for this issue, I noticed a typo in the tooltip of some fields in the nav pane controls of the find panel )_

![image](https://github.com/boltex/leojs/assets/847716/fa746cac-8cd3-4788-ac4a-95cd46669daa)

It works exactly like in Leo, (searches as you type, enter to 'freeze' and get detailed results, clear to unfreeze, etc...)  but it shows its results in the 'GOTO' pane, what will open automatically upon finding results to show. You can even navigate the results in the Goto pane with the cursor keys! (up / down, etc) and LeoJS will 'jump ' from one result to the next to show it to you in the outline+body 

![image](https://github.com/boltex/leojs/assets/847716/c4d67745-2c59-4327-987b-8cb404dfbcd9)

**Comment by tbpassin** [comment]
It's not quite the same as the Nav pane.  You have a kind of combination of Leo's Find and Nav panes.  However, your search results are better/more readable than for Leo's Find pane.  I'll need to play with them more to see if they are close enough to make me happy.
