### ISSUE TITLE
Closing and re-opening a file that has external files shows the message 'Changes to external files were detected. Nodes refreshed.'

### ISSUE THREAD

**Issue by boltex** [boltex/leojs#89]
As if the external file check was still active from the old commander or something... :/

(Just an annoying notification that does not corrupt files, but still a very annoying glitch)

**Comment by edreamleo** [comment]
@boltex What's the status of this issue?

**Comment by boltex** [comment]
This issue is still 'todo'. It's the next one i'll tackle in the next few days.

(Not looked into since I filed it - so I'll have to re-check if still an issue as it may have been indirectly fixed.)

**Comment by edreamleo** [comment]
@boltex Thanks for the clarification.

**Comment by boltex** [comment]
I tried to reproduce but I cannot reproduce: The message would only appear if an external file was changed, and **if it was specifically an @clean.** (because there is a comparison on load time to be checked, and the original Leo does the same, which totally makes sense)

Maybe that's what happened originally and I didn't notice that crucial detail 😄 

Therefore I'm closing this unless something else pops up in regards to unexpected message about 'changes detected' at load time.
