### ISSUE TITLE
Finish 'doHook' system for plugins to react to common Leo actions & events

### ISSUE THREAD

**Issue by boltex** [boltex/leojs#90]
To supplement the exposition of g, c p and the vscode object that are already available for scripts, finish 'hook' system for plugins to react to common event

**Comment by tbpassin** [comment]
You do know that you have a tiger by the tail, don't you. Felix?  Your work will never be done with!

**Comment by boltex** [comment]
@tbpassin To be honest, there's less things to fix / broken than I expected after releasing the beta! 😄 

(but still I expect being pretty busy putting out little fires here and there for the next few weeks for sure!)
