### ISSUE TITLE
LeoJS icon in sidebar missing in vsc but not vscodium

### ISSUE THREAD

**Issue by tbpassin** [boltex/leojs#98]
I no longer see the LeoJS icon in the icon strip at the left of the VSC window.  It's there in VSCodium.  Without this icon, when I closed the last LeoJS window I could no longer use it until I restarted VSC.  I didn't see a setting to restore the icon, and I don't know what if anything I did to cause the situation.

**Comment by boltex** [comment]
There is no code that shows/hide the icon nor any conditional logic on that. So its probably a misclick/right click issue. Those can also be dragged out to the other sidebar, etc.

Try right-clicking on the sidebar. It's probably just hidden (you can check/uncheck which ones are shown with the checkmark beside them.) 

![image](https://github.com/boltex/leojs/assets/847716/740b4325-5a7a-4f35-99d3-427df20f18cd)

**Comment by tbpassin** [comment]
Right-clicking did the trick.  Thanks!
